#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
	herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4      # Use the super key as the main modifier

# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Control-h     shift left
hc keybind $Mod-Control-j     shift down
hc keybind $Mod-Control-k     shift up
hc keybind $Mod-Control-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s       split   bottom  0.5
hc keybind $Mod-v       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Shift-h       resize left +$resizestep
hc keybind $Mod-Shift-j       resize down +$resizestep
hc keybind $Mod-Shift-k       resize up +$resizestep
hc keybind $Mod-Shift-l       resize right +$resizestep

# tags
tag_names=( I II III IV V VI VII VIII IX X )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if ! [ -z "$key" ] ; then
		hc keybind "$Mod-$key" use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
	fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-f floating toggle
hc keybind $Mod-Shift-q remove
hc keybind $Mod-Shift-space cycle_layout -1
hc keybind $Mod-f floating toggle
hc keybind $Mod-g fullscreen toggle
hc keybind $Mod-t pseudotile

# floating windows settings
hc set snap_distance 10
hc set snap_gap 10
hc set raise_on_focus 0
hc set raise_on_click 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
hc set focus_stealing_prevention 1
hc set update_dragged_clients 1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
#hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
#hc keybind $Mod-c cycle
#hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#222222'
hc set frame_bg_normal_color '#F59BB0'
hc set frame_bg_active_color '#F59BB0'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 10

hc attr theme.border_width 5
hc attr theme.normal.color '#474747'
hc attr theme.active.color '#F59BB0'
hc attr theme.urgent.color '#C5C8A8'

hc attr theme.outer_width 3
hc attr theme.outer_color '#222222'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0

hc pad 0 35 5 5 5

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
